version: 2

models:
  - name: decoded_logs
    description: "Decoded log data with parsed event information"
    columns:
      - name: chainid
        description: "Chain ID (1 for Ethereum mainnet)"
        tests:
          - not_null
      - name: address
        description: "Contract address that emitted the log"
        tests:
          - not_null
      - name: block_number
        description: "Block number where event occurred"
        tests:
          - not_null
      - name: transaction_hash
        description: "Hash of the transaction"
        tests:
          - not_null
      - name: log_index
        description: "Index of log within the transaction"
      - name: event_name
        description: "Name of the decoded event"
      - name: event_signature
        description: "Event signature (topic0)"
      - name: decoded_data
        description: "Decoded event parameters as JSON"
