version: 2

sources:
  - name: etherscan_raw
    description: "Centralized Ethereum blockchain data from Etherscan API"
    schema: etherscan_raw
    tables:
      - name: logs
        description: "Raw log data from all contract addresses across all chains"
        columns:
          - name: chainid
            description: "Chain ID (1 for Ethereum mainnet)"
            tests:
              - not_null
          - name: address
            description: "Contract address that emitted the log"
            tests:
              - not_null
          - name: topics
            description: "JSON array of indexed event topics"
            tests:
              - not_null
          - name: data
            description: "Non-indexed event data (hex encoded)"
          - name: block_number
            description: "Block number where event occurred"
            tests:
              - not_null
          - name: block_hash
            description: "Hash of the block"
          - name: time_stamp
            description: "Unix timestamp of the block"
          - name: gas_price
            description: "Gas price for the transaction"
          - name: gas_used
            description: "Gas used by the transaction"
          - name: log_index
            description: "Index of log within the transaction"
          - name: transaction_hash
            description: "Hash of the transaction"
            tests:
              - not_null
          - name: transaction_index
            description: "Index of transaction within the block"