name: "marts"
version: "1.0.0"
config-version: 2

profile: "marts"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  marts:
    materialized: table
    +indexes:
      - columns: ["token_address", "block_number"]
        type: btree
      - columns: ["transaction_hash"]
        type: btree
      - columns: ["datetime"]
        type: btree
    transfers:
      +indexes:
        - columns: ["from_address", "block_number"]
          type: btree
        - columns: ["to_address", "block_number"]
          type: btree
    approvals:
      +indexes:
        - columns: ["owner", "block_number"]
          type: btree
        - columns: ["spender", "block_number"]
          type: btree
