version: 2

models:
  - name: transfers
    description: "ERC20 token transfer events decoded from raw logs"
    columns:
      - name: chainid
        description: "Chain ID (1 for Ethereum mainnet)"
        tests: [not_null]
      - name: token_address
        description: "Address of the ERC20 token contract"
        tests: [not_null]
      - name: from_address
        description: "Address sending the tokens"
        tests: [not_null]
      - name: to_address
        description: "Address receiving the tokens"
        tests: [not_null]
      - name: amount
        description: "Amount of tokens transferred (in smallest unit)"
        tests: [not_null]
      - name: block_number
        description: "Block number where event occurred"
        tests: [not_null]
      - name: datetime
        description: "Timestamp of the event"
        tests: [not_null]
      - name: transaction_hash
        description: "Hash of the transaction containing the event"
        tests: [not_null]
      - name: log_index
        description: "Index of the log within the transaction"
        tests: [not_null]

  - name: approvals
    description: "ERC20 token approval events decoded from raw logs"
    columns:
      - name: chainid
        description: "Chain ID (1 for Ethereum mainnet)"
        tests: [not_null]
      - name: token_address
        description: "Address of the ERC20 token contract"
        tests: [not_null]
      - name: owner
        description: "Address that owns the tokens"
        tests: [not_null]
      - name: spender
        description: "Address approved to spend tokens"
        tests: [not_null]
      - name: amount
        description: "Amount of tokens approved (in smallest unit)"
        tests: [not_null]
      - name: block_number
        description: "Block number where event occurred"
        tests: [not_null]
      - name: datetime
        description: "Timestamp of the event"
        tests: [not_null]
      - name: transaction_hash
        description: "Hash of the transaction containing the event"
        tests: [not_null]
      - name: log_index
        description: "Index of the log within the transaction"
        tests: [not_null]
